volumes:
  gsm3_data:
    driver: local

services:
  management_panel:
    build: .
    container_name: GSManager3
    #image: xiaozhu674/gameservermanager:latest
    image: repo.local.com/gameservermanager:3.9.3
    user: root                       
    ports:
      # GSM3管理面板端口
      - 3001:3001 
      # 游戏端口，按需映射
      - 27015:27015
    volumes:
    #steam用户数据目录 不建议修改
      - /home/gsm/game_data:/home/.config 
      - /home/gsm/game_data:/home/.local
      - /home/gsm/game_file:/home/steam/games
    #root用户数据目录 不建议修改
      - /home/gsm/game_data:/root/.config 
      - /home/gsm/game_data:/root/.local   
      - /home/gsm/game_file:/root/steam/games 
    #面板数据，请勿改动
      - gsm3_data:/root/server/data 
    environment:
      - TZ=Asia/Shanghai              # 设置时区
      - SERVER_PORT=3001              # GSM3服务端口
    stdin_open: true                  # 保持STDIN打开
    tty: true                         # 分配TTY
    restart:
      unless-stopped
    
    # 如果需要，取消注释下面的行来限制资源
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '4.0'
    #       memory: 8G
    #     reservations:
    #       cpus: '2.0'
    #       memory: 4G

